
parameters:
  buildConfiguration: "Release"
  pool: "ubuntu-latest"


  jobs:
    - job: "DotNet"
      pool: ${{ parameters.pool }}
      steps:
        - checkout: self
          submodules: recursive

        - template: "./build.yml"

