
parameters:
  buildConfiguration: "Release"
  pool: "ubuntu-latest"


jobs:
  - job: "DotNet"
    pool: 
      vmImage: "ubuntu-latest"

    steps:
    - checkout: self
      submodules: recursive

    - template: "./build.yml"