
parameters:
  buildConfiguration: "Release"
  pool: "ubuntu-latest"

stages:
  - pool: ${{ parameters.pool }}
  - stage: Build
    jobs:
      - job: "DotNet"
        steps:
          - checkout: self
            submodules: recursive

          - template: "./build.yml"

      - job: "Docker"
        template: "../Docker/build.yml"
