
parameters:
- buildConfiguration: "Release"
- pool: "ubuntu-latest"
- name: "image"
  default: "edge-image"
  type: string


jobs:
  - job: "DotNet"
    pool: 
      vmImage: ${{ parameters.pool }}

    steps:
    - checkout: self
      submodules: recursive

    - template: "./build.yml"